// --- FILE: data.js ---

// 1. DỮ LIỆU HUNG KHÍ (Màu Xanh Dương)
export const meansData = [
    { en: "Powder Drug", vi: "Ma tuý bột" }, { en: "Hook", vi: "Móc câu" }, { en: "Whip", vi: "Roi da" },
    { en: "Razor Blade", vi: "Lưỡi lam" }, { en: "Bees", vi: "Đàn ong" }, { en: "Metal Wire", vi: "Dây thép" },
    { en: "Starvation", vi: "Chết đói" }, { en: "Scarf", vi: "Khăn choàng" }, { en: "Dismember", vi: "Chặt tay chân" },
    { en: "Machine", vi: "Máy móc" }, { en: "Poisonous Needle", vi: "Kim tẩm độc" }, { en: "Punch", vi: "Đấm" },
    { en: "Plastic Bag", vi: "Túi ni lông" }, { en: "Belt", vi: "Thắt lưng" }, { en: "Kick", vi: "Đá" },
    { en: "Electric Current", vi: "Dòng điện" }, { en: "Kerosene", vi: "Dầu hoả" }, { en: "Liquid Drug", vi: "Thuốc dạng lỏng" },
    { en: "Electric Baton", vi: "Dùi cui điện" }, { en: "Match", vi: "Diêm" }, { en: "Machete", vi: "Mã tấu" },
    { en: "Explosives", vi: "Thuốc nổ" }, { en: "Pesticide", vi: "Thuốc trừ sâu" }, { en: "Wrench", vi: "Mỏ lếch" },
    { en: "Bat", vi: "Gậy" }, { en: "Bury", vi: "Chôn" }, { en: "Poisonous Gas", vi: "Khí độc" },
    { en: "Trophy", vi: "Cúp" }, { en: "Venomous Scorpion", vi: "Bọ cạp độc" }, { en: "Gunpowder", vi: "Thuốc súng" },
    { en: "Overdose", vi: "Quá liều" }, { en: "Folding Chair", vi: "Ghế xếp" }, { en: "Lighter", vi: "Bật lửa" },
    { en: "Towel", vi: "Khăn lau" }, { en: "Amoeba", vi: "Trùng AMIP" }, { en: "Brick", vi: "Gạch" },
    { en: "Trowel", vi: "Cái bay" }, { en: "Injection", vi: "Tiêm" }, { en: "Alcohol", vi: "Cồn" },
    { en: "Wine", vi: "Rượu" }, { en: "Dagger", vi: "Dao găm" }, { en: "Hammer", vi: "Búa" },
    { en: "Mercury", vi: "Thuỷ ngân" }, { en: "Steel Tube", vi: "Ống thép" }, { en: "Pill", vi: "Viên thuốc" },
    { en: "Box Cutter", vi: "Dao rọc giấy" }, { en: "Dirty Water", vi: "Nước bẩn" }, { en: "Blender", vi: "Máy xay" },
    { en: "Axe", vi: "Rìu" }, { en: "Death Ray", vi: "Tia chết chóc" }, { en: "Video Game Console", vi: "Máy chơi game" },
    { en: "Bite & Tear", vi: "Cắn và xé" }, { en: "Sulfuric Acid", vi: "Axit Sunfuric" }, { en: "Venomous Snake", vi: "Rắn độc" },
    { en: "Radiation", vi: "Phóng xạ" }, { en: "Drown", vi: "Chết đuối" }, { en: "Metal Chain", vi: "Xích sắt" },
    { en: "Pistol", vi: "Súng lục" }, { en: "Push", vi: "Đẩy" }, { en: "Sniper", vi: "Bắn tỉa" },
    { en: "Candlestick", vi: "Giá đỡ nến" }, { en: "Potted Plant", vi: "Chậu cây" }, { en: "Packing Tape", vi: "Băng dính gói hàng" },
    { en: "Bamboo Tip", vi: "Mũi tre" }, { en: "Arsenic", vi: "Thạch tín" }, { en: "Black Widow", vi: "Nhện goá phụ" },
    { en: "Wire", vi: "Dây điện" }, { en: "Bumbbell", vi: "Tạ" }, { en: "Arson", vi: "Phóng hoả" },
    { en: "Blood Release", vi: "Cắt tiết" }, { en: "Crutch", vi: "Nạng" }, { en: "E-Bike", vi: "Xe điện" },
    { en: "Laser Shark", vi: "Cá mập laze" }, { en: "Illegal Drug", vi: "Thuốc cấm" }, { en: "Mad Dog", vi: "Chó dại" },
    { en: "Ice Skates", vi: "Giày trượt băng" }, { en: "Throat Slit", vi: "Cắt cổ" }, { en: "Smoke", vi: "Khói" },
    { en: "Rope", vi: "Dây thừng" }, { en: "Scissors", vi: "Kéo" }, { en: "Dirty Hands", vi: "Tay bẩn" },
    { en: "Chemicals", vi: "Hoá chất" }, { en: "Blood Sample", vi: "Mẫu máu" }, { en: "Stone", vi: "Cục đá" },
    { en: "Drill", vi: "Máy khoan" }, { en: "Chainsaw", vi: "Cưa máy" }, { en: "Plague", vi: "Bệnh dịch" },
    { en: "Cleaver", vi: "Dao phay" }, { en: "Pillow", vi: "Gối" }, { en: "Knife&Fork", vi: "Dao & nĩa" },
    { en: "Surgery", vi: "Phẫu thuật" }, { en: "Work", vi: "Làm việc" }, { en: "Unarmed", vi: "Tay không" },
    { en: "Virus", vi: "Vi rút" }, { en: "Sculpture", vi: "Bức tượng" }, { en: "Locked Room", vi: "Phòng khoá kín" },
    { en: "Incense Sticks", vi: "Nhang" }, { en: "Killer Teapot", vi: "Ấm trà sát thủ" }, { en: "Laundry Detergent", vi: "Bột giặt" },
    { en: "Canteen", vi: "Bình toong" }, { en: "Liquid Nitrogen", vi: "Ni tơ lỏng" }, { en: "Broken Glass", vi: "Mảnh vỡ kính" },
    { en: "Vietnamese Sword", vi: "Kiếm VietNam" }, { en: "Compass", vi: "Compa" }, { en: "Rice Field Eel", vi: "Lươn đồng" },
    { en: "Datura Stramonium", vi: "Mạn đà la" }, { en: "Pollen", vi: "Phấn hoa" }, { en: "Contact Adhesive", vi: "Keo con chó" },
    { en: "Car Battery", vi: "Ắc quy" }, { en: "Rake", vi: "Bồ cào" }, { en: "Selfie Stick", vi: "Gậy selfie" },
    { en: "Rusty Iron Nail", vi: "Đinh rỉ" }, { en: "Lego Toys", vi: "Đồ chơi Lego" }, { en: "Coal Briquette", vi: "Than tổ ong" },
    { en: "Matchlock Gun", vi: "Súng hoả mai" }, { en: "Black Magic", vi: "Bùa ngải" }, { en: "Bamboo Pipe", vi: "Điếu cày" },
    { en: "Incense Burner", vi: "Lư hương" }, { en: "Nail Clipper", vi: "Cắt móng tay" }, { en: "Pickleball Paddle", vi: "Vợt pickleball" },
    { en: "Centipede", vi: "Rết" }, { en: "Rove Beetle", vi: "Kiến ba khoang" }, { en: "Electric Fishing Device", vi: "Bộ chích điện" },
    { en: "Rodenticide", vi: "Thuốc chuột" }, { en: "Thermal Bottle", vi: "Bình thuỷ" }, { en: "Hair Dryer", vi: "Máy sấy tóc" },
    { en: "Hoe", vi: "Cuốc đất" }, { en: "Tennis Racket", vi: "Vợt tennis" }, { en: "Bleach", vi: "Nước tẩy" },
    { en: "Super Glue", vi: "Keo 502" }, { en: "Nux-Vomica", vi: "Hạt mã tiền" }, { en: "Garlic", vi: "Tỏi" },
    { en: "Shoulder Pole", vi: "Đòn gánh" }, { en: "Water Well", vi: "Giếng" }, { en: "Roll Forming Machine", vi: "Máy cán tôn" },
    { en: "Outboard Motor", vi: "Động cơ cano" }, { en: "Crowbar", vi: "Xà beng" }, { en: "Sickle", vi: "Liềm" },
    { en: "Gas Cylinder", vi: "Bình ga" }, { en: "Cement Mixer", vi: "Máy trộn xi măng" }, { en: "Red Plastic Stool", vi: "Ghế nhựa đỏ" },
    { en: "Pith Helmet", vi: "Mũ cối" }, { en: "Durian", vi: "Sầu riêng" }, { en: "Rice Grinder", vi: "Cối xay lúa" },
    { en: "Brush Knife", vi: "Rựa phát cỏ" }, { en: "Sticking Knife", vi: "Dao chọc tiết lợn" }, { en: "Shovel", vi: "Xẻng" },
    { en: "Long Saber", vi: "Trường đao" }, { en: "Kali Xyanua", vi: "Đường (Kali Xyanua)" }, { en: "Gelsemiun Elegans", vi: "Cây lá ngón" },
    { en: "Beer", vi: "Bia" }, { en: "Water Jar", vi: "Lu nước" }, { en: "Badminton Racket", vi: "Vợt cầu lông" },
    { en: "Diy Crossbow", vi: "Nỏ tự chế" }, { en: "Metal Cage", vi: "Lồng sắt" }, { en: "Gunny Sack", vi: "Bao bố" },
    { en: "Hunting Spear", vi: "Phóng lợn" }, { en: "Weeding Knife", vi: "Dao làm cỏ" }, { en: "Amantica Muscaria", vi: "Nấm độc" },
    { en: "Nuts And Seeds", vi: "Hạt các loại" }
];

// 2. DỮ LIỆU TANG VẬT (Màu Đỏ)
export const cluesData = [
    { en: "Gloves", vi: "Găng tay" }, { en: "Tea Leaves", vi: "Lá trà" }, { en: "Jacket", vi: "Áo khoác" },
    { en: "Telephone", vi: "Điện thoại" }, { en: "Herbal Medicine", vi: "Thảo dược" }, { en: "Seasoning", vi: "Gia vị" },
    { en: "Comics", vi: "Truyện tranh" }, { en: "Cup", vi: "Cốc" }, { en: "Coins", vi: "Đồng xu" },
    { en: "Note", vi: "Giấy nhớ" }, { en: "Cosmetic Mask", vi: "Mặt nạ dưỡng da" }, { en: "Certificate", vi: "Văn bằng" },
    { en: "Leather Shoe", vi: "Giày da" }, { en: "Fax", vi: "Máy Fax" }, { en: "Soft Drink", vi: "Nước ngọt" },
    { en: "Cassette Tape", vi: "Băng cát xét" }, { en: "Luggage", vi: "Hành lý" }, { en: "Soap", vi: "Xà phòng" },
    { en: "Love Letter", vi: "Thư tình" }, { en: "Bone", vi: "Xương" }, { en: "Mosquito Coil", vi: "Nhang muỗi" },
    { en: "Speaker", vi: "Loa" }, { en: "Paint", vi: "Sơn" }, { en: "Usb Flash Drive", vi: "Ổ Usb" },
    { en: "Office Supplies", vi: "Văn phòng phẩm" }, { en: "Banknote", vi: "Tiền giấy" }, { en: "Hanger", vi: "Móc áo" },
    { en: "Plant", vi: "Cây" }, { en: "Dentures", vi: "Răng giả" }, { en: "Steamed Buns", vi: "Bánh bao" },
    { en: "Lipstick", vi: "Son môi" }, { en: "Model", vi: "Mô hình" }, { en: "Air Conditioning", vi: "Máy điều hoà" },
    { en: "Juice", vi: "Nước ép" }, { en: "Necklace", vi: "Vòng cổ" }, { en: "Cockroach", vi: "Gián" },
    { en: "Computer Disk", vi: "Đĩa máy vi tính" }, { en: "Newspaper", vi: "Báo" }, { en: "Flute", vi: "Sáo" },
    { en: "Lunch Box", vi: "Hộp cơm trưa" }, { en: "Peanut", vi: "Đậu phộng" }, { en: "Documents", vi: "Tài liệu" },
    { en: "Photograph", vi: "Bức ảnh" }, { en: "Dice", vi: "Xí ngầu" }, { en: "Badge", vi: "Huy hiệu" },
    { en: "Bandage", vi: "Băng gạc" }, { en: "Ink", vi: "Mực" }, { en: "Push Pin", vi: "Ghim" },
    { en: "Mask", vi: "Mặt nạ" }, { en: "Stockings", vi: "Vớ dài" }, { en: "Umbrella", vi: "Ô dù" },
    { en: "Nail", vi: "Đinh" }, { en: "Fan", vi: "Quạt" }, { en: "Ants", vi: "Kiến" }, { en: "Skull", vi: "Hộp sọ" },
    { en: "Antique", vi: "Đồ cổ" }, { en: "Rose", vi: "Hoa hồng" }, { en: "Cleaning Cloth", vi: "Mảnh vải lau" },
    { en: "Insect", vi: "Côn trùng" }, { en: "Numbers", vi: "Con số" }, { en: "Tissue", vi: "Khăn giấy" },
    { en: "Map", vi: "Bản đồ" }, { en: "Test Tube", vi: "Ống nghiệm" }, { en: "Notebook", vi: "Sổ tay" },
    { en: "Switch", vi: "Công tắc" }, { en: "Fingernails", vi: "Móng tay" }, { en: "Dust", vi: "Bụi bặm" },
    { en: "Curtains", vi: "Rèm" }, { en: "Confidential Letter", vi: "Mật thư" }, { en: "Syringe", vi: "Ống tiêm" },
    { en: "Oil Painting", vi: "Tranh sơn dầu" }, { en: "Ice", vi: "Nước đá" }, { en: "Violin", vi: "Vĩ cầm" },
    { en: "Lock", vi: "Ổ khoá" }, { en: "Tool Box", vi: "Hộp dụng cụ" }, { en: "Needle & Thread", vi: "Kim và chỉ" },
    { en: "Lottery Ticket", vi: "Vé số" }, { en: "Blood", vi: "Máu" }, { en: "Tweezers", vi: "Cái nhíp" },
    { en: "Light Bulb", vi: "Bóng đèn tròn" }, { en: "Food Ingredients", vi: "Nguyên liệu thực phẩm" },
    { en: "Surveillance Camera", vi: "Camera giám sát" }, { en: "Perfume", vi: "Nước hoa" }, { en: "Diary", vi: "Nhật ký" },
    { en: "Mirror", vi: "Gương" }, { en: "Mark", vi: "Dấu vết" }, { en: "Earrings", vi: "Hoa tai" },
    { en: "Mosquito", vi: "Con muỗi" }, { en: "Mobile Phone", vi: "Điện thoại di động" }, { en: "Video Camera", vi: "Máy quay phim" },
    { en: "ID Card", vi: "Thẻ căn cước" }, { en: "Snacks", vi: "Đồ ăn nhẹ" }, { en: "Gift", vi: "Món quà" },
    { en: "Button", vi: "Khuy Áo" }, { en: "Hat", vi: "Mũ" }, { en: "Prescription", vi: "Toa thuốc" },
    { en: "Electric Circuit", vi: "Mạch điện" }, { en: "Graffiti", vi: "Hình vẽ đường phố" }, { en: "Rat", vi: "Con chuột" },
    { en: "Internet Cable", vi: "Dây cáp mạng" }, { en: "Calender", vi: "Lịch" }, { en: "Riddle", vi: "Câu đố" },
    { en: "Toothpicks", vi: "Tăm xỉa răng" }, { en: "Take-out", vi: "Đồ ăn mang về" }, { en: "Flip-Flop", vi: "Dép lào" },
    { en: "Maze", vi: "Mê cung" }, { en: "Sponge", vi: "Miếng bọt biển" }, { en: "Iron", vi: "Bàn ủi" },
    { en: "Key", vi: "Chìa khoá" }, { en: "Betting Chips", vi: "Chíp cá cược" }, { en: "Sample", vi: "Mẫu vật" },
    { en: "Sack", vi: "Bao tải" }, { en: "Jewelry", vi: "Trang sức" }, { en: "Magazine", vi: "Tạp chí" },
    { en: "Cigarette Ash", vi: "Tàn thuốc lá" }, { en: "Envelope", vi: "Phong bì" }, { en: "Carton", vi: "Thùng các tông" },
    { en: "Table Lamp", vi: "Đèn bàn" }, { en: "Hairpin", vi: "Kẹp tóc" }, { en: "Bread", vi: "Bánh mì" },
    { en: "Dog Fur", vi: "Lông chó" }, { en: "Sawdust", vi: "Mùn cưa" }, { en: "Wig", vi: "Tóc giả" },
    { en: "Leaf", vi: "Lá cây" }, { en: "Spider", vi: "Nhện" }, { en: "Cake", vi: "Bánh ngọt" },
    { en: "Flyer", vi: "Tờ rơi" }, { en: "Chalk", vi: "Phấn" }, { en: "Oil Stain", vi: "Vết dầu" },
    { en: "Sock", vi: "Tất" }, { en: "Powder", vi: "Bột" }, { en: "Computer Mouse", vi: "Chuột máy tính" },
    { en: "Timber", vi: "Gỗ" }, { en: "Puzzle", vi: "Mảnh ghép" }, { en: "Hourglass", vi: "Đồng hồ cát" },
    { en: "Menu", vi: "Thực đơn" }, { en: "Invitation Card", vi: "Thiệp mời" }, { en: "Spinning Top", vi: "Con quay" },
    { en: "Cigarette Butt", vi: "Mẩu thuốc lá" }, { en: "Red Wine", vi: "Rượu vang đỏ" }, { en: "Cat", vi: "Con mèo" },
    { en: "Watch", vi: "Đồng hồ đeo tay" }, { en: "Glue", vi: "Keo dán" }, { en: "Broom", vi: "Cây chổi" },
    { en: "Ring", vi: "Nhẫn" }, { en: "Candy", vi: "Kẹo" }, { en: "Playing Cards", vi: "Thẻ bài" },
    { en: "Sunglasses", vi: "Kính râm" }, { en: "Suit", vi: "Bộ com lê" }, { en: "Pocket Watch", vi: "Đồng hồ bỏ túi" },
    { en: "Lens", vi: "Thấu kính" }, { en: "Bell", vi: "Chuông" }, { en: "Cotton", vi: "Bông" },
    { en: "Spring", vi: "Lò xo" }, { en: "Computer", vi: "Máy vi tính" }, { en: "Plastic", vi: "Nhựa" },
    { en: "Handcuffs", vi: "Còng tay" }, { en: "Toy", vi: "Đồ chơi" }, { en: "Sand", vi: "Cát" },
    { en: "Vegetables", vi: "Rau củ quả" }, { en: "Briefs", vi: "Quần lót nam" }, { en: "Coffee", vi: "Cà phê" },
    { en: "Bracelet", vi: "Vòng tay" }, { en: "Book", vi: "Sách" }, { en: "Helmet", vi: "Mũ bảo hiểm" },
    { en: "Eggs", vi: "Trứng" }, { en: "Cigar", vi: "Xì gà" }, { en: "Iou Note", vi: "Giấy ghi nợ" },
    { en: "Gear", vi: "Bánh răng" }, { en: "Dirt", vi: "Bùn" }, { en: "Panties", vi: "Quần lót nữ" },
    { en: "Signature", vi: "Chữ ký" }, { en: "IV Bag", vi: "Túi truyền dịch" }, { en: "Receipt", vi: "Hoá đơn" },
    { en: "Tattoo", vi: "Hình xăm" }, { en: "Dictionary", vi: "Từ điển" }, { en: "Postal Stamp", vi: "Tem thư" },
    { en: "Express Courier", vi: "Chuyển phát nhanh" }, { en: "Apple", vi: "Quả táo" }, { en: "Leather Bag", vi: "Túi da" },
    { en: "Tie", vi: "Cà vạt" }, { en: "Toy Blocks", vi: "Đồ chơi xếp khối" }, { en: "Uniform", vi: "Đồng phục" },
    { en: "Puppet", vi: "Con rối" }, { en: "Bullet", vi: "Viên đạn" }, { en: "Rubber Stamp", vi: "Con dấu" },
    { en: "Wallet", vi: "Ví" }, { en: "Hair", vi: "Tóc" }, { en: "Raincoat", vi: "Áo mưa" },
    { en: "Surgical Mask", vi: "Khẩu trang y tế" }, { en: "Safety Pin", vi: "Kim băng" }, { en: "Mahjong Tiles", vi: "Quân mạc chược" }
];

// 3. DỮ LIỆU PHÁP Y (Màu Vàng - Tím - Xanh Lá)
export const forensicData = {
    purple: { en: "Cause Of Death", vi: "Nguyên Nhân Tử Vong", items: ["Ngạt thở", "Chấn thương nghiêm trọng", "Mất máu", "Ốm đau/Bệnh tật", "Ngộ độc", "Tai nạn"] },
    green: [
        { en: "Location Of Crime", vi: "Địa Điểm Gây Án", items: ["Phòng khách", "Phòng ngủ", "Nhà kho", "Phòng tắm", "Nhà bếp", "Ban công"] },
        { en: "Location Of Crime", vi: "Địa Điểm Gây Án", items: ["Sân chơi", "Phòng học", "Ký túc xá", "Căng tin", "Thang máy", "Nhà vệ sinh"] },
        { en: "Location Of Crime", vi: "Địa Điểm Gây Án", items: ["Quán rượu", "Hiệu sách", "Nhà hàng", "Khách sạn", "Bệnh viện", "Công trường"] },
        { en: "Location Of Crime", vi: "Địa Điểm Gây Án", items: ["Nhà nghỉ mát", "Công viên", "Siêu thị", "Trường học", "Rừng", "Ngân hàng"] }
    ],
    yellow: [
        { en: "State Of The Scene", vi: "Tình Trạng Hiện Trường", items: ["Nhiều mảnh, mẫu, khúc", "Tro tàn", "Vết nước bẩn", "Nứt nẻ", "Lộn xộn", "Ngăn nắp"] },
        { en: "Hint On Corpse", vi: "Dấu Vết Trên Thi Thể", items: ["Đầu", "Ngực", "Tay", "Chân", "Một phần", "Toàn thân"] },
        { en: "Noticed By Stranger", vi: "Phát Hiện Bởi Người Lạ", items: ["Tiếng động đột ngột", "Tiếng động kéo dài", "Ngửi thấy", "Nhìn thấy", "Hành vi", "Không gì cả"] },
        { en: "Time Of Death", vi: "Thời Điểm Tử Vong", items: ["Rạng sáng", "Buổi sáng", "Buổi trưa", "Buổi chiều", "Buổi tối", "Đêm khuya"] },
        { en: "Victim's Clothes", vi: "Quần Áo Nạn Nhân", items: ["Gọn gàng", "Xốc xếch", "Thanh lịch", "Tồi tàn", "Kỳ quái", "Khoả thân"] },
        { en: "General Impression", vi: "Ấn Tượng Chung", items: ["Bình thường", "Sáng tạo", "Khả nghi", "Tàn độc", "Khủng khiếp", "Hồi hộp"] },
        { en: "Weather", vi: "Thời Tiết Khi Xảy Ra", items: ["Nắng", "Giông bão", "Khô hanh", "Ẩm ướt", "Lạnh", "Nóng"] },
        { en: "Victim's Expression", vi: "Biểu Hiện Của Nạn Nhân", items: ["Bình yên", "Quá sức", "Sợ hãi", "Đau đớn", "Đờ đẫn", "Giận dữ"] },
        { en: "Victim's Identity", vi: "Danh Tính Nạn Nhân", items: ["Trẻ con", "Thanh niên", "Trung niên", "Người già", "Nam", "Nữ"] },
        { en: "Duration Of Crime", vi: "Khoảng Thời Gian Gây Án", items: ["Chớp nhoáng", "Nhanh gọn", "Từ từ", "Kéo dài", "Vài ngày", "Chưa rõ"] },
        { en: "Victim's Occupation", vi: "Nghề Nghiệp Nạn Nhân", items: ["Sếp", "Chuyên gia", "Công nhân", "Sinh viên", "Thất nghiệp", "Nghỉ hưu"] },
        { en: "Evidence Left Behind", vi: "Chứng Cứ Để Lại", items: ["Tự nhiên", "Thuộc về nghệ thuật", "Chữ viết", "Nguỵ tạo", "Cá nhân", "Không liên quan"] },
        { en: "Victim's Build", vi: "Ngoại Hình Nạn Nhân", items: ["To lớn", "Gầy", "Cao", "Lùn", "Biến dạng", "Cân đối"] },
        { en: "Trace At The Scene", vi: "Dấu Vết Tại Hiện Trường", items: ["Vân tay", "Dấu chân", "Vết bầm tím", "Vết máu", "Dịch cơ thể", "Chưa rõ"] },
        { en: "Sudden Incident", vi: "Sự Cố Đột Ngột", items: ["Mất điện", "Hoả hoạn", "Xung đột", "Mất đồ có giá trị", "Tiếng thét", "Không có gì"] },
        { en: "Murderer's Personality", vi: "Tính Cách Thủ Phạm", items: ["Ngạo mạn", "Đê hèn", "Hung dữ", "Tham lam", "Mạnh mẽ", "Biến thái"] },
        { en: "In Progress", vi: "Nạn Nhân Tử Vong Khi Đang", items: ["Giải trí", "Nghỉ ngơi", "Họp mặt", "Buôn bán", "Thăm hỏi", "Ăn uống"] },
        { en: "Day Of Crime", vi: "Thời Điểm Gây Án", items: ["Ngày thường", "Cuối tuần", "Mùa xuân", "Mùa hè", "Mùa thu", "Mùa đông"] },
        { en: "Motive Of Crime", vi: "Động Cơ Gây Án", items: ["Căm thù", "Quyền lực", "Tiền bạc", "Tình yêu", "Ghen tị", "Công lý"] },
        { en: "Social Relationship", vi: "Quan Hệ Xã Hội", items: ["Người thân", "Bạn bè", "Đồng nghiệp", "Chủ/tớ", "Người yêu", "Người xa lạ"] },
        { en: "Corpse Condition", vi: "Tình Trạng Thi Thể", items: ["Vẫn còn ấm", "Cứng đờ", "Bị phân huỷ", "Không nguyên vẹn", "Nguyên vẹn", "Méo mó"] }
    ]
};

// 4. DỮ LIỆU VAI TRÒ
export const ROLES = {
    // Phe Điều Tra (Màu Xanh/Vàng)
    FORENSIC: { id: 'FORENSIC', name: "Pháp Y", team: "BLUE", desc: "Biết Sát Nhân. Đưa ra gợi ý.", limit: 1 },
    INVESTIGATOR: { id: 'INVESTIGATOR', name: "Điều Tra Viên", team: "BLUE", desc: "Phá án tìm Sát Nhân.", limit: 99 },
    WITNESS: { id: 'WITNESS', name: "Nhân Chứng", team: "BLUE", desc: "Biết Phe Hung Thủ (Không rõ ai là ai).", limit: 1 },
    WITNESS_GUARD: { id: 'WITNESS_GUARD', name: "Bảo Vệ Nhân Chứng", team: "BLUE", desc: "Biết Nhân Chứng. Bảo vệ họ.", limit: 1 },
    TECHNICIAN: { id: 'TECHNICIAN', name: "Kỹ Thuật Viên", team: "BLUE", desc: "Có thể hỏi Pháp Y về 1 vật chứng.", limit: 1, active: true },
    PSYCHOLOGIST: { id: 'PSYCHOLOGIST', name: "Nhà Tâm Lý Học", team: "BLUE", desc: "Khi tiết lộ: Pháp Y đổi 1 gợi ý.", limit: 1, active: true },
    VICTIM_FAMILY: { id: 'VICTIM_FAMILY', name: "Thân Nhân", team: "BLUE", desc: "Khi tiết lộ: Pháp Y đổi 1 gợi ý.", limit: 1, active: true },
    CONSULTING_DETECTIVE: { id: 'CONSULTING_DETECTIVE', name: "Thám Tử Cố Vấn", team: "BLUE", desc: "Hỏi Pháp Y 1 câu Yes/No.", limit: 1, active: true },
    
    // Phe Hung Thủ (Màu Đỏ)
    MURDERER: { id: 'MURDERER', name: "Sát Nhân", team: "RED", desc: "Chọn Hung khí & Tang vật. Giết người.", limit: 1 },
    ACCOMPLICE: { id: 'ACCOMPLICE', name: "Tòng Phạm", team: "RED", desc: "Biết Sát Nhân. Hỗ trợ gây án.", limit: 1 },
    SMART_ACCOMPLICE: { id: 'SMART_ACCOMPLICE', name: "TP Thông Minh", team: "RED", desc: "Biết phe Đỏ. Tráo 1 Hung khí đêm.", limit: 1 },
    SCAPEGOAT: { id: 'SCAPEGOAT', name: "Kẻ Thế Mạng", team: "RED", desc: "Chọn 1 người phe Đỏ để đỡ đòn 1 lần.", limit: 1 },

    // Phe Thứ 3 (Màu Tím/Xám)
    INSIDE_MAN: { id: 'INSIDE_MAN', name: "Tay Trong", team: "GRAY", desc: "Kế thừa Sát Nhân nếu chưa bị lộ.", limit: 1 }
};